name: Nightly builds

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64
          - i686
          - x86_64
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install -U --upgrade-strategy=eager -r requirements.txt
      - name: docker qemu multi-arch
        if: matrix.arch != 'x86_64'
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset --persistent yes
      - name: Build
        run: |
          SOURCE_DATE_EPOCH=$(git show -s --format=%ct) ./build.sh ${{ matrix.arch }} "" master
      - name: Get file name
        id: vars
        run: |
          echo "file_name=$(cd dist && ls *.*)" >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.vars.outputs.file_name }}
          path: dist/*
